apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
type: Opaque
data:
  STACKIT_PROJECT_ID: {{ .Values.stackitCredentials.projectID | b64enc }}
  STACKIT_SERVICE_ACCOUNT_KEY: {{ .Values.stackitCredentials.serviceAccountKey | b64enc }}