{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "stackit-exporter.fullname" . }}
  labels:
    {{- toYaml .Values.serviceMonitor.label | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "stackit-exporter.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      interval: {{ .Values.serviceMonitor.interval }}
      path: {{ .Values.serviceMonitor.path }}
{{- end }}