name: Test & Lint

on:
  push:
    branches:
      - main
      - dev
      - 'dependabot/**'

jobs:
  lint-go-code:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.5'

      - name: Install golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: 'v2.3.1'

      - name: Run golangci-lint
        run: golangci-lint run --allow-parallel-runners --timeout=5m --config=golang-ci.yaml

  test-go-code:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.5'

      - name: Install Dependencies
        run: go get -v -t -d ./...

      - name: Test Go Code
        run: go test -cover ./internal/...